### PR TITLE
Add `resetMode` function to reset mode to OS preference

### LINKED ISSUE #6: feature request: add `resetMode` functionality
if you want to go back to the OS preference, then this is needed

### PR DESCRIPTION
**Pull request by ollema**
closes #6

### CODE REVIEW

**Comment by ollema** [comment]
@huntabyte not sure about the test, can one assume that dark mode is the default OS preference in the test environment? or does it instead work because one can assume that 
```ts
/** Get the OS preference */
export function getModeOsPrefers(): boolean {
	const prefersLightMode = window.matchMedia('(prefers-color-scheme: light)').matches;
	modeOsPrefers.set(prefersLightMode);
	return prefersLightMode;
}
```
will default to `false`?

**Comment by huntabyte** [comment]
I believe it does default to false, I didn't spend _too_ much time trying to see how I could mock that out, but it looks good!

**Comment by huntabyte** [comment]
Let me know once it's good to merge/release!

**Comment by ollema** [comment]
> Let me know once it's good to merge/release!

I think it should be good to go now, forgot to include this in the README.md but fixed now

**Comment by huntabyte** [comment]
Thank you! @ollema

**Pull request merged**
